apiVersion: v1
kind: Secret
metadata:
  name: db-postgres-secret
  namespace: credit-pipeline-namespace
  labels:
    app: credit-pipeline-app
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-postgres-configmap
  namespace: credit-pipeline-namespace
  labels:
    app: credit-pipeline-app
data:
  init.sql: |-
    CREATE USER ms_deal_admin NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD 'ms_deal_admin';
    CREATE USER ms_deal_user NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD 'ms_deal_user';
    CREATE USER ms_deal_test NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD 'ms_deal_test';
    CREATE DATABASE ms_deal OWNER ms_deal_admin ENCODING 'UTF8' CONNECTION LIMIT 100;
    \c ms_deal
    CREATE SCHEMA ms_deal AUTHORIZATION ms_deal_admin;
    CREATE SCHEMA ms_deal_liquibase AUTHORIZATION ms_deal_admin;
    ALTER DEFAULT PRIVILEGES FOR ROLE ms_deal_admin GRANT USAGE ON SCHEMAS TO ms_deal_user;
    ALTER DEFAULT PRIVILEGES FOR ROLE ms_deal_admin GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO ms_deal_user;
    ALTER DEFAULT PRIVILEGES FOR ROLE ms_deal_admin IN SCHEMA ms_deal GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO ms_deal_user;
    ALTER DEFAULT PRIVILEGES FOR ROLE ms_deal_admin IN SCHEMA ms_deal GRANT EXECUTE ON FUNCTIONS TO ms_deal_user;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ms_deal TO ms_deal_user;
    GRANT USAGE ON SCHEMA ms_deal TO ms_deal_user;
    ALTER DEFAULT PRIVILEGES FOR ROLE ms_deal_admin IN SCHEMA ms_deal_liquibase GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO ms_deal_user;
    ALTER DEFAULT PRIVILEGES FOR ROLE ms_deal_admin IN SCHEMA ms_deal_liquibase GRANT EXECUTE ON FUNCTIONS TO ms_deal_user;
    GRANT USAGE ON SCHEMA ms_deal_liquibase TO ms_deal_user;
    ALTER DEFAULT PRIVILEGES FOR ROLE ms_deal_admin GRANT USAGE ON SCHEMAS TO ms_deal_test;
    ALTER DEFAULT PRIVILEGES FOR ROLE ms_deal_admin GRANT SELECT ON TABLES TO ms_deal_test;
    ALTER DEFAULT PRIVILEGES FOR ROLE ms_deal_admin IN SCHEMA ms_deal GRANT SELECT ON TABLES TO ms_deal_test;
    ALTER DEFAULT PRIVILEGES FOR ROLE ms_deal_admin IN SCHEMA ms_deal_liquibase GRANT SELECT ON TABLES TO ms_deal_test;
    GRANT USAGE ON SCHEMA ms_deal TO ms_deal_test;
    GRANT USAGE ON SCHEMA ms_deal_liquibase TO ms_deal_test;
    ALTER DATABASE ms_deal set search_path TO 'ms_deal';
---
apiVersion: v1
kind: Service
metadata:
  name: db-postgres-service
  namespace: credit-pipeline-namespace
  labels:
    app: credit-pipeline-app
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30183
      targetPort: 5432
  selector:
    app: credit-pipeline-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-postgres-deployment
  namespace: credit-pipeline-namespace
  labels:
    app: credit-pipeline-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-pipeline-app
  template:
    metadata:
      labels:
        app: credit-pipeline-app
    spec:
      volumes:
        - name: db-postgres-configmap
          configMap:
            name: db-postgres-configmap
        - name: db-postgres-secret
          secret:
            secretName: db-postgres-secret
      containers:
        - name: db-postgres
          image: postgres:13.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: db-postgres-secret
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: db-postgres-configmap
          resources:
            requests:
              memory: "64Mi"
            limits:
              memory: "128Mi"