apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-configmap
  namespace: credit-pipeline-namespace
  labels:
    app: credit-pipeline-app
data:
  ALLOW_ANONYMOUS_LOGIN: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: credit-pipeline-namespace
  labels:
    app: credit-pipeline-app
spec:
  type: NodePort
  ports:
    - port: 2181
      nodePort: 30181
      targetPort: 2181
  selector:
    app: credit-pipeline-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  namespace: credit-pipeline-namespace
  labels:
    app: credit-pipeline-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-pipeline-app
  template:
    metadata:
      labels:
        app: credit-pipeline-app
    spec:
      volumes:
        - name: zookeeper-configmap
          configMap:
            name: zookeeper-configmap
      containers:
        - image: wurstmeister/zookeeper
          imagePullPolicy: IfNotPresent
          name: zookeeper
          ports:
            - containerPort: 2181
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              valueFrom:
                configMapKeyRef:
                  key: ALLOW_ANONYMOUS_LOGIN
                  name: zookeeper-configmap
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "256Mi"