apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: kafka-config
  name: kafka-config
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_CFG_ZOOKEEPER_CONNECT: "10.100.61.33:2181"
  KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
  KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
  ALLOW_PLAINTEXT_LISTENER: "yes"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-service
  name: kafka-service
spec:
  type: NodePort
  ports:
    - port: 9092
      nodePort: 30182
      targetPort: 9092
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      hostname: kafka
      containers:
        - env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BROKER_ID
                  name: kafka-config
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_CFG_ZOOKEEPER_CONNECT
                  name: kafka-config
            - name: KAFKA_CFG_LISTENERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_CFG_LISTENERS
                  name: kafka-config
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_CFG_ADVERTISED_LISTENERS
                  name: kafka-config
            - name: ALLOW_PLAINTEXT_LISTENER
              valueFrom:
                configMapKeyRef:
                  key: ALLOW_PLAINTEXT_LISTENER
                  name: kafka-config
          image: bitnami/kafka:latest
          imagePullPolicy: IfNotPresent
          name: kafka
          ports:
            - containerPort: 9092
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "512m"