apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-configmap
  namespace: credit-pipeline-namespace
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper-service:2181"
  KAFKA_LISTENERS: "PLAINTEXT://:9092"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service:9092"
  ALLOW_PLAINTEXT_LISTENER: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: credit-pipeline-namespace
spec:
  type: NodePort
  ports:
    - port: 9092
      nodePort: 30182
      targetPort: 9092
  selector:
    app: kafka-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: credit-pipeline-namespace
  labels:
    app: kafka-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      volumes:
        - name: kafka-configmap
          configMap:
            name: kafka-configmap
      containers:
        - env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BROKER_ID
                  name: kafka-configmap
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_ZOOKEEPER_CONNECT
                  name: kafka-configmap
            - name: KAFKA_LISTENERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_LISTENERS
                  name: kafka-configmap
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_ADVERTISED_LISTENERS
                  name: kafka-configmap
            - name: ALLOW_PLAINTEXT_LISTENER
              valueFrom:
                configMapKeyRef:
                  key: ALLOW_PLAINTEXT_LISTENER
                  name: kafka-configmap
          image: wurstmeister/kafka
          imagePullPolicy: IfNotPresent
          name: kafka
          ports:
            - containerPort: 9092
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"