apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-conveyor-configmap
  namespace: credit-pipeline-namespace
data:
  APP_NAME: "ms-conveyor.jar"
  CONVEYOR_AMOUNT_BIG: "2500000"
  CONVEYOR_AMOUNT_MIDDLE: "500000"
  CONVEYOR_INSURANCE_PERCENT: "3"
  CONVEYOR_INSURANCE_SALARY_CLIENT_PERCENT: "0"
  CONVEYOR_RATE_AMOUNT_BIG: "5"
  CONVEYOR_RATE_AMOUNT_MIDDLE: "16"
  CONVEYOR_RATE_AMOUNT_SMALL: "27"
  CONVEYOR_RATE_BASE: "10"
  CONVEYOR_RATE_INSURANCE: "10"
  CONVEYOR_RATE_SALARY_CLIENT: "12"
  CONVEYOR_RATE_TERM_BIG: "55"
  CONVEYOR_RATE_TERM_MIDDLE: "35"
  CONVEYOR_RATE_TERM_SMALL: "15"
  CONVEYOR_TERM_BIG: "120"
  CONVEYOR_TERM_MIDDLE: "60"
  LOG_LEVEL: "debug"
  SERVER_INCLUDE_STACKTRACE: "always"
  SERVER_PORT: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-conveyor-service
  namespace: credit-pipeline-namespace
spec:
  type: NodePort
  ports:
    - port: 8081
      nodePort: 30185
      targetPort: 8081
  selector:
    app: ms-conveyor-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-conveyor-deployment
  namespace: credit-pipeline-namespace
  labels:
    app: ms-conveyor-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-conveyor-app
  template:
    metadata:
      labels:
        app: ms-conveyor-app
    spec:
      volumes:
        - name: ms-conveyor-configmap
          configMap:
            name: ms-conveyor-configmap
      containers:
        - envFrom:
            - configMapRef:
                name: ms-conveyor-configmap
          image: lexana/java-service:ms-conveyor
          name: ms-conveyor
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "256Mi"
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              path: /actuator/health/readiness
              port: 8081
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              path: /actuator/health/liveness
              port: 8081