apiVersion: v1
kind: Secret
metadata:
  name: ms-deal-secret
  namespace: credit-pipeline-namespace
data:
  DATASOURCE_USERNAME: bXNfZGVhbF91c2Vy
  DATASOURCE_PASSWORD: bXNfZGVhbF91c2Vy
  LIQUIBASE_USERNAME: bXNfZGVhbF9hZG1pbg==
  LIQUIBASE_PASSWORD: bXNfZGVhbF9hZG1pbg==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-deal-configmap
  namespace: credit-pipeline-namespace
data:
  APP_NAME: "ms-deal-0.1.0.jar"
  SERVER_PORT: "8082"
  DATASOURCE_URL: "jdbc:postgresql://db-postgres-service:5432/ms_deal?currentSchema=ms_deal"
  DATASOURCE_SCHEMA: "ms_deal"
  DATASOURCE_LIQUIBASE_SCHEMA: "ms_deal_liquibase"
  KAFKA_URL: "kafka-service:9092"
  KAFKA_CLIENT_ID: "deal"
  KAFKA_TOPIC_FINISH_REGISTRATION: "finish-registration"
  KAFKA_TOPIC_CREATE_DOCUMENTS: "create-documents"
  KAFKA_TOPIC_SEND_DOCUMENTS: "send-documents"
  KAFKA_TOPIC_SEND_SES: "send-ses"
  KAFKA_TOPIC_CREDIT_ISSUED: "credit-issued"
  KAFKA_TOPIC_APPLICATION_DENIED: "application-denied"
  FEIGN_CONNECT_TIMEOUT: "5000"
  FEIGN_READ_TIMEOUT: "5000"
  FEIGN_LOG_LEVEL: "full"
  LOG_LEVEL: "DEBUG"
  CONVEYOR_URL: "http://ms-conveyor-service:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-deal-service
  namespace: credit-pipeline-namespace
spec:
  type: NodePort
  ports:
    - port: 8082
      nodePort: 30184
      targetPort: 8082
  selector:
    app: ms-deal-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-deal-deployment
  namespace: credit-pipeline-namespace
  labels:
    app: ms-deal-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-deal-app
  template:
    metadata:
      labels:
        app: ms-deal-app
    spec:
      volumes:
        - name: ms-deal-configmap
          configMap:
            name: ms-deal-configmap
        - name: ms-deal-secret
          secret:
            secretName: ms-deal-secret
      containers:
        - envFrom:
            - configMapRef:
                name: ms-deal-configmap
            - secretRef:
                name: ms-deal-secret
          image: lexana/java-service:ms-deal
          name: ms-deal
          ports:
            - containerPort: 8082
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "512Mi"
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              path: /actuator/health/readiness
              port: 8082
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              path: /actuator/health/liveness
              port: 8082
      restartPolicy: Always