apiVersion: v1
kind: Secret
metadata:
  name: ms-deal-secret
  namespace: credit-pipeline-namespace
  labels:
    app: credit-pipeline-app
data:
  DATASOURCE_USERNAME: bXNfZGVhbF91c2Vy
  DATASOURCE_PASSWORD: bXNfZGVhbF91c2Vy
  LIQUIBASE_USERNAME: bXNfZGVhbF9hZG1pbg==
  LIQUIBASE_PASSWORD: bXNfZGVhbF9hZG1pbg==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-deal-configmap
  namespace: credit-pipeline-namespace
  labels:
    app: credit-pipeline-app
data:
  APP_NAME: "ms-deal-0.1.0.jar"
  SERVER_PORT: "8082"
  DATASOURCE_URL: "jdbc:postgresql://10.1.1.36:5432/ms_deal?currentSchema=ms_deal"
  DATASOURCE_SCHEMA: "ms_deal"
  DATASOURCE_LIQUIBASE_SCHEMA: "ms_deal_liquibase"
  KAFKA_URL: "10.1.1.38:9092"
  KAFKA_CLIENT_ID: "deal"
  KAFKA_TOPIC_FINISH_REGISTRATION: "finish-registration"
  KAFKA_TOPIC_CREATE_DOCUMENTS: "create-documents"
  KAFKA_TOPIC_SEND_DOCUMENTS: "send-documents"
  KAFKA_TOPIC_SEND_SES: "send-ses"
  KAFKA_TOPIC_CREDIT_ISSUED: "credit-issued"
  KAFKA_TOPIC_APPLICATION_DENIED: "application-denied"
  FEIGN_CONNECT_TIMEOUT: "5000"
  FEIGN_READ_TIMEOUT: "5000"
  FEIGN_LOG_LEVEL: "full"
  LOG_LEVEL: "DEBUG"
  CONVEYOR_URL: "http://10.1.1.39:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-deal-service
  namespace: credit-pipeline-namespace
  labels:
    app: credit-pipeline-app
spec:
  type: NodePort
  ports:
    - port: 8082
      nodePort: 30184
      targetPort: 8082
  selector:
    app: credit-pipeline-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-deal-deployment
  namespace: credit-pipeline-namespace
  labels:
    app: credit-pipeline-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-pipeline-app
  template:
    metadata:
      labels:
        app: credit-pipeline-app
    spec:
      volumes:
        - name: ms-deal-configmap
          configMap:
            name: ms-deal-configmap
        - name: ms-deal-secret
          secret:
            secretName: ms-deal-secret
      containers:
        - env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  key: APP_NAME
                  name: ms-deal-configmap
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: SERVER_PORT
                  name: ms-deal-configmap
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATASOURCE_URL
                  name: ms-deal-configmap
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DATASOURCE_USERNAME
                  name: ms-deal-secret
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DATASOURCE_PASSWORD
                  name: ms-deal-secret
            - name: DATASOURCE_SCHEMA
              valueFrom:
                configMapKeyRef:
                  key: DATASOURCE_SCHEMA
                  name: ms-deal-configmap
            - name: DATASOURCE_LIQUIBASE_SCHEMA
              valueFrom:
                configMapKeyRef:
                  key: DATASOURCE_LIQUIBASE_SCHEMA
                  name: ms-deal-configmap
            - name: LIQUIBASE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: LIQUIBASE_USERNAME
                  name: ms-deal-secret
            - name: LIQUIBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: LIQUIBASE_PASSWORD
                  name: ms-deal-secret
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_URL
                  name: ms-deal-configmap
            - name: KAFKA_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_CLIENT_ID
                  name: ms-deal-configmap
            - name: KAFKA_TOPIC_FINISH_REGISTRATION
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_TOPIC_FINISH_REGISTRATION
                  name: ms-deal-configmap
            - name: KAFKA_TOPIC_CREATE_DOCUMENTS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_TOPIC_CREATE_DOCUMENTS
                  name: ms-deal-configmap
            - name: KAFKA_TOPIC_SEND_DOCUMENTS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_TOPIC_SEND_DOCUMENTS
                  name: ms-deal-configmap
            - name: KAFKA_TOPIC_SEND_SES
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_TOPIC_SEND_SES
                  name: ms-deal-configmap
            - name: KAFKA_TOPIC_CREDIT_ISSUED
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_TOPIC_CREDIT_ISSUED
                  name: ms-deal-configmap
            - name: KAFKA_TOPIC_APPLICATION_DENIED
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_TOPIC_APPLICATION_DENIED
                  name: ms-deal-configmap
            - name: FEIGN_CONNECT_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: FEIGN_CONNECT_TIMEOUT
                  name: ms-deal-configmap
            - name: FEIGN_READ_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: FEIGN_READ_TIMEOUT
                  name: ms-deal-configmap
            - name: FEIGN_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: FEIGN_LOG_LEVEL
                  name: ms-deal-configmap
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: LOG_LEVEL
                  name: ms-deal-configmap
            - name: CONVEYOR_URL
              valueFrom:
                configMapKeyRef:
                  key: CONVEYOR_URL
                  name: ms-deal-configmap
          image: lexana/java-service:ms-deal
          name: ms-deal
          ports:
            - containerPort: 8082
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "512Mi"
      restartPolicy: Always