apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  namespace: credit-pipeline-namespace
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: [ 'localhost:9090' ]

      - job_name: 'ms-conveyor'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: [ 'ms-conveyor-service:8081' ]
      
      - job_name: 'ms-deal'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: [ 'ms-deal-service:8082' ]
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: credit-pipeline-namespace
spec:
  type: NodePort
  ports:
    - port: 9090
      nodePort: 30186
      targetPort: 9090
  selector:
    app: prometheus-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: credit-pipeline-namespace
  labels:
    app: prometheus-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-app
  template:
    metadata:
      labels:
        app: prometheus-app
    spec:
      volumes:
        - name: prometheus-configmap
          configMap:
            name: prometheus-configmap
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /etc/prometheus/
              name: prometheus-configmap
          resources:
            requests:
              memory: "64Mi"
            limits:
              memory: "128Mi"