apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.kafka.name }}-configmap
  namespace: {{ .Values.kafka.namespace }}
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper-service:2181"
  KAFKA_LISTENERS: "PLAINTEXT://:9092"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service:9092"
  ALLOW_PLAINTEXT_LISTENER: "yes"