apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kafka.name }}-deployment
  namespace: {{ .Values.kafka.namespace }}
  labels:
    app: {{ .Values.kafka.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.kafka.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.name }}
    spec:
      volumes:
        - name: {{ .Values.kafka.name }}-configmap
          configMap:
            name: {{ .Values.kafka.name }}-configmap
      containers:
        - env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BROKER_ID
                  name: {{ .Values.kafka.name }}-configmap
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_ZOOKEEPER_CONNECT
                  name: {{ .Values.kafka.name }}-configmap
            - name: KAFKA_LISTENERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_LISTENERS
                  name: {{ .Values.kafka.name }}-configmap
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_ADVERTISED_LISTENERS
                  name: {{ .Values.kafka.name }}-configmap
            - name: ALLOW_PLAINTEXT_LISTENER
              valueFrom:
                configMapKeyRef:
                  key: ALLOW_PLAINTEXT_LISTENER
                  name: {{ .Values.kafka.name }}-configmap
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Values.kafka.name }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
            limits:
              memory: {{ .Values.resources.limits.memory }}