apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.name }}-service
  namespace: {{ .Values.kafka.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.kafka.name }}