apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prometheus.name }}-deployment
  namespace: {{ .Values.prometheus.namespace }}
  labels:
    app: {{ .Values.prometheus.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.prometheus.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.prometheus.name }}
    spec:
      volumes:
        - name: {{ .Values.prometheus.name }}-configmap
          configMap:
            name: {{ .Values.prometheus.name }}-configmap
      containers:
        - name: {{ .Values.prometheus.name }}
          image: prom/prometheus
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - mountPath: /etc/prometheus/
              name: {{ .Values.prometheus.name }}-configmap
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
            limits:
              memory: {{ .Values.resources.limits.memory }}