apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.msDeal.name }}-configmap
  namespace: {{ .Values.msDeal.namespace }}
data:
  APP_NAME: "ms-deal-0.1.0.jar"
  SERVER_PORT: "8082"
  DATASOURCE_URL: "jdbc:postgresql://db-postgres-service:5432/ms_deal?currentSchema=ms_deal"
  DATASOURCE_SCHEMA: "ms_deal"
  DATASOURCE_LIQUIBASE_SCHEMA: "ms_deal_liquibase"
  KAFKA_URL: "kafka-service:9092"
  KAFKA_CLIENT_ID: "deal"
  KAFKA_TOPIC_FINISH_REGISTRATION: "finish-registration"
  KAFKA_TOPIC_CREATE_DOCUMENTS: "create-documents"
  KAFKA_TOPIC_SEND_DOCUMENTS: "send-documents"
  KAFKA_TOPIC_SEND_SES: "send-ses"
  KAFKA_TOPIC_CREDIT_ISSUED: "credit-issued"
  KAFKA_TOPIC_APPLICATION_DENIED: "application-denied"
  FEIGN_CONNECT_TIMEOUT: "5000"
  FEIGN_READ_TIMEOUT: "5000"
  FEIGN_LOG_LEVEL: "full"
  LOG_LEVEL: "DEBUG"
  CONVEYOR_URL: "http://ms-conveyor-service:8081"