apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.msDeal.name }}-secret
  namespace: {{ .Values.msDeal.namespace }}
data:
  DATASOURCE_USERNAME: bXNfZGVhbF91c2Vy
  DATASOURCE_PASSWORD: bXNfZGVhbF91c2Vy
  LIQUIBASE_USERNAME: bXNfZGVhbF9hZG1pbg==
  LIQUIBASE_PASSWORD: bXNfZGVhbF9hZG1pbg==