apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.msConveyor.name }}-configmap
  namespace: {{ .Values.msConveyor.namespace }}
data:
  APP_NAME: "ms-conveyor.jar"
  CONVEYOR_AMOUNT_BIG: "2500000"
  CONVEYOR_AMOUNT_MIDDLE: "500000"
  CONVEYOR_INSURANCE_PERCENT: "3"
  CONVEYOR_INSURANCE_SALARY_CLIENT_PERCENT: "0"
  CONVEYOR_RATE_AMOUNT_BIG: "5"
  CONVEYOR_RATE_AMOUNT_MIDDLE: "16"
  CONVEYOR_RATE_AMOUNT_SMALL: "27"
  CONVEYOR_RATE_BASE: "10"
  CONVEYOR_RATE_INSURANCE: "10"
  CONVEYOR_RATE_SALARY_CLIENT: "12"
  CONVEYOR_RATE_TERM_BIG: "55"
  CONVEYOR_RATE_TERM_MIDDLE: "35"
  CONVEYOR_RATE_TERM_SMALL: "15"
  CONVEYOR_TERM_BIG: "120"
  CONVEYOR_TERM_MIDDLE: "60"
  LOG_LEVEL: "debug"
  SERVER_INCLUDE_STACKTRACE: "always"
  SERVER_PORT: "8081"