apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.msConveyor.name }}-service
  namespace: {{ .Values.msConveyor.namespace }}
spec:
  selector:
    app: {{ .Values.msConveyor.name }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
